### ISSUE TITLE
container process caused: exec: "./start.sh": permission denied: unknown

### ISSUE THREAD

**Issue by alanmoleapfive** [4everland/arweave-docker#1]
Status: Downloaded newer image for 4everland/arweave-node:testnet
Creating arweave-docker_arweave-node_1 ... error

ERROR: for arweave-docker_arweave-node_1  Cannot start service arweave-node: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start.sh": permission denied: unknown

ERROR: for arweave-node  Cannot start service arweave-node: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start.sh": permission denied: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by cachalots** [comment]
@alanmoleapfive  try `chmod +x ./start.sh` before `docker-compose up`

**Comment by alanmoleapfive** [comment]
ok,but  more hour  not block  gen
logs
Attaching to arweave-docker_miner_1, arweave-docker_arweave-node_1
arweave-node_1  | mkdir: cannot create directory ?/data/arweave?: No such file or directory
arweave-node_1  | WARN: ************************************************************************
arweave-node_1  | WARN: Your maximum number of open file descriptors is currently set to 1024.
arweave-node_1  | WARN: We recommend setting that limit to 1000000 or higher.
arweave-node_1  | WARN: 
arweave-node_1  | WARN: Otherwise, consider setting your max_connections setting to something
arweave-node_1  | WARN: lower than your file descriptor limit.
arweave-node_1  | WARN: ************************************************************************
arweave-node_1  | 
arweave-node_1  | Launching Erlang Virtual Machine...
arweave-node_1  | Exec: /app/erts-12.2.1/bin/erlexec -noinput +Bd -boot /app/releases/2.5.1.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /app/lib -config /app/releases/2.5.1.0/sys.config -args_file /app/releases/2.5.1.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main init data_dir /data/arweave requests_per_minute_limit 9999999999999999999999999999999999999999 disk_space 100000000 max_disk_pool_data_root_buffer_mb 100 tx_propagation_parallelization 3 max_emitters 1 enable arql_tags_index enable serve_tx_data_without_limits port 1984
arweave-node_1  | Root: /app
arweave-node_1  | /app
arweave-node_1  | Initialising RandomX dataset for fast packing. Key: <<"ZGVmYXVsdCBhcndlYXZlIDIuNSBwYWNrIGtleQ">>. The process may take several minutes.
arweave-node_1  | RandomX dataset initialisation complete.
arweave-node_1  | Initialising RandomX dataset for fast hashing. Swap height: 0, Key: <<"QXJ3ZWF2ZSBHZW5lc2lzIFJhbmRvbVggS2V5">>. The process may take several minutes.
arweave-node_1  | RandomX dataset initialisation for swap height 0 complete.
arweave-node_1  | Joined the Arweave network successfully.
arweave-node_1  | No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
arweave-node_1  | No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
arweave-node_1  | No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.

**Comment by alanmoleapfive** [comment]
./miner.sh  not  work ok

**Comment by cachalots** [comment]
@alanmoleapfive try ```chmod +x ./miner.sh``` before ```docker-compose up```
